### ISSUE TITLE
无法登陆 

### ISSUE THREAD

**Issue by PhoenixLeeSin** [conghaonet/GitHao#11]
无法登陆 老哥 我在学习flutter clone下该项目后 无法登录  404 我已经挂了梯子了

**Comment by prateekmedia** [comment]
@PhoenixLeeSin 
同样，您是否启用了双重身份验证？

**Comment by PhoenixLeeSin** [comment]
解决了 设置问题

**Comment by prateekmedia** [comment]
@PhoenixLeeSin 您是如何解决的
